#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 14 08:58:49 2021

@author: tkpci
"""


import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
import os

# create RSR
def create_RSR(center, FWHM):
    
    wave = np.arange(2,6,0.01)
    rsr = norm.pdf(wave,center,FWHM/2.3548)
    rsr = rsr/max(rsr)
    plt.plot(wave,rsr)
    
    return wave,rsr
  

# create tape 5    
def create_tape5(tape5_info,filename):
    
    
    # check if all variables are there
    if 'lat'not in tape5_info:
        tape5_info['lat'] = 43.1566   # Rochester NY lat
    if 'lon'not in tape5_info:
        tape5_info['lon'] = 77.6088   # Rochester NY lat
    if 'lst'not in tape5_info:
        tape5_info['lst'] = 500    # lower fire temp
    if 'emissivity'not in tape5_info:
        tape5_info['emissivity'] = 0           # assign albedo as 1
    if 'alt'not in tape5_info:
        tape5_info['alt'] = 0   # sea level   
    if 'time'not in tape5_info:
        tape5_info['time'] = 12.0
    if 'iday'not in tape5_info:
        tape5_info['iday'] = 1
    if 'filepath'not in tape5_info:
        tape5_info['filepath'] = '/cis/staff2/tkpci/modtran/tape5_predefined/'

    
    # create tape5 file 
    filename = tape5_info['filepath'] +filename    
    f = open(filename,"w+")

    
    # write header information
    f.write("TS  %1.0f    2    2   -1    0    0    0    0    0    0    1    1    0 %6.3f %6.2f\n" % (tape5_info['profile'],tape5_info['lst'],1-tape5_info['emissivity']))
    f.write("T   4F   0   0.00000       1.0       1.0 F F F         0.000\n");
    f.write("    1    0    0    3    0    0     0.000     0.000     0.000     0.000  %8.3f\n" % tape5_info['alt']);
    f.write("   %2.0f    0    0\n" % tape5_info['lev']);

    # write footer information
    f.write("   750.000  %8.3f   180.000     0.000     0.000     0.000    0          0.000\n" % tape5_info['alt']);
    f.write("    1    0  %3.0f    0\n" % tape5_info['iday']);
    f.write("  %8.3f  %8.3f     0.000     0.000  %8.3f     0.000     0.000     0.000\n" % (tape5_info['lat'],tape5_info['lon'],tape5_info['time']));
    f.write("     2.000     6.000     0.020     0.025RM        M  A   \n");
    f.write("    0\n");
    f.close()
    
def runModtran(tape5_name, tape6_name):
    
    print('Modtran run: ',tape5_name)
    
    command = 'cp /cis/staff2/tkpci/modtran/tape5_predefined/' + tape5_name + ' /cis/staff2/tkpci/modtran/tape5/tape5'
    
    os.system(command) 
    
    command = 'cd /cis/staff2/tkpci/modtran/tape5\n' \
              'ln -s /dirs/pkg/Mod4v3r1/DATA\n' \
              '/dirs/pkg/Mod4v3r1/Mod4v3r1.exe'
    
    os.system(command) 

    command = 'cp /cis/staff2/tkpci/modtran/tape5/tape6 /cis/staff2/tkpci/modtran/tape6_predefined/' + tape6_name 
    os.system(command) 
    
    command = 'rm /cis/staff2/tkpci/modtran/tape5/*'
    os.system(command)
    
   
def main():
    
    tape5_name = 'tape5'
    tape6_name = 'tape6'
    
    tape5_info= {}
    tape5_info['emissivity'] = 0.95   #fixed for fire
    tape5_info['profile'] = 2   # 1 = tropical, 2 = mid-lat summer, 3 = mid-lat winter etc.
    tape5_info['lst'] = 500    # fire temperature
    
    create_tape5(tape5_info,tape5_name)
    runModtran(tape5_name,tape6_name)
    
    
    
    
    
    
    
    
    