#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 19 13:40:10 2022

@author: tkpci
"""

import numpy as np
import matplotlib.pyplot as plt


def load_RSR(sensor='TIRS2_10'):
    
    # load RSR of specified sensor
    
    filepath = '/cis/staff2/tkpci/modtran/RSR/'
    if sensor == 'MOD31':
        filename = filepath + 'MODIS_31.csv'
        data = np.genfromtxt(filename, delimiter=',')
        wave = data[:,0]
        rsr = data[:,1]
    elif sensor == 'MOD32':
        filename = filepath + 'MODIS_32.csv'
        data = np.genfromtxt(filename, delimiter=',')
        wave = data[:,0]
        rsr = data[:,2]
    elif sensor == 'TIRS2_10':
        filename = filepath + 'TIRS2.csv'
        data = np.genfromtxt(filename, delimiter=',')
        wave = data[:,0]
        rsr = data[:,1]
    elif sensor == 'TIRS2_11':
        filename = filepath + 'TIRS2.csv'
        data = np.genfromtxt(filename, delimiter=',')
        wave = data[:,0]
        rsr = data[:,2]
        
    return wave, rsr






wave, rsr = load_RSR(sensor='TIRS2_11')





b0 = np.ones(T_diff.shape)

y = np.array(dataOut['skintemp'])
y = y.flatten()

x = []
# b0
x.append(b0)
# b1
x.append(T_plus)
# b2
x.append(T_plus*e_diff)
# b3
x.append(T_plus*e_change)
# b4
x.append(T_diff)
# b5
x.append(T_diff*e_diff)
# b6
x.append(T_diff*e_change)
# b7
x.append(quad)
    
x = np.array(x).T

coeff, residuals, rank, s = np.linalg.lstsq(x,y,rcond=None)